questions_answers = {

    "fees kya hai": "BCA AIML fees is 95,000 per year.",
    "hostel available hai": "Yes, hostel facility is available for boys and girls.",
    "admission process kya hai": "You can apply online through the college website.",
    "exam kab honge": "Exams will start next month.",
    "library available hai": "Yes, library is available for all students.",
    "college timing kya hai": "College timing is 9 AM to 5 PM.",
    "attendance kitni chahiye": "Minimum 75% attendance is required.",
    "canteen available hai": "Yes, college has a canteen facility.",
    "wifi available hai": "Yes, free WiFi is available on campus.",
    "uniform compulsory hai": "No, uniform is not compulsory.",
    "placement hoti hai": "Yes, placement opportunities are available.",
    "bca course duration kya hai": "BCA course duration is 3 years.",
    "mba available hai": "Yes, MBA course is available.",
    "scholarship milti hai": "Yes, scholarships are available for eligible students.",
    "hostel fees kya hai": "Hostel fees is around 80,000 per year.",
    "college ka address kya hai": "The college is located in Greater Noida.",
    "online classes hoti hai": "Yes, online classes are available when needed.",
    "sports facility hai": "Yes, sports facilities are available.",
    "gym available hai": "Yes, gym facility is available for students.",
    "ragging allowed hai": "No, ragging is strictly prohibited.",
    "admission last date kya hai": "Admission last date will be updated on the website.",
    "computer lab hai": "Yes, advanced computer labs are available.",
    "faculty achi hai": "Yes, experienced faculty members are available.",
    "bus facility hai": "Yes, transport facility is available.",
    "internship milti hai": "Yes, internship opportunities are provided.",
    "semester kitne hote hai": "There are 6 semesters in BCA.",
    "btech available hai": "Yes, BTech course is available.",
    "medical facility hai": "Yes, medical facilities are available on campus.",
    "annual fest hota hai": "Yes, annual cultural fest is organized every year.",
    "college government hai": "No, it is a private university.",
    "class kab start hogi": "Classes will start next month.",
    "admission open hai": "Yes, admissions are currently open.",
    "id card compulsory hai": "Yes, ID card is mandatory inside campus.",
    "holiday kab hai": "Holiday schedule is available on the college portal.",
    "notes milenge": "Yes, notes are provided by faculty.",
    "practical labs hai": "Yes, practical labs are available.",
    "hostel me ac room hai": "Yes, AC rooms are available in hostel.",
    "mess food kaisa hai": "Mess food quality is good.",
    "college timing saturday": "Saturday timing is 9 AM to 1 PM.",
    "library timing kya hai": "Library timing is 8 AM to 8 PM.",
    "girls hostel hai": "Yes, separate girls hostel is available.",
    "boys hostel hai": "Yes, separate boys hostel is available.",
    "attendance fine lagta hai": "Yes, shortage of attendance may lead to fine.",
    "college ka website kya hai": "You can visit the official college website.",
    "faculty support karti hai": "Yes, faculty members are very supportive.",
    "coding clubs hai": "Yes, coding clubs are available.",
    "hackathon hota hai": "Yes, hackathons are organized regularly.",
    "ai course available hai": "Yes, AI specialization courses are available.",
    "machine learning padhate hai": "Yes, machine learning subjects are included.",
    "python padhate hai": "Yes, Python programming is taught.",
    "java padhate hai": "Yes, Java programming is available.",
    "c language padhate hai": "Yes, C programming is taught.",
    "college me events hote hai": "Yes, technical and cultural events are organized.",
    "fest kab hoga": "Fest dates will be announced soon.",
    "exam online honge": "Exam mode depends on university guidelines.",
    "result kab aayega": "Results will be declared after exams.",
    "rechecking hoti hai": "Yes, rechecking option is available.",
    "back exam hota hai": "Yes, back exams are conducted.",
    "admit card kaha milega": "Admit card can be downloaded from portal.",
    "portal login kaise kare": "Use your enrollment number and password.",
    "erp available hai": "Yes, ERP portal is available.",
    "fee online pay kar sakte hai": "Yes, online payment option is available.",
    "emi option hai": "Yes, EMI and loan facilities are available.",
    "education loan milta hai": "Yes, education loan assistance is available.",
    "college me strictness hai": "Yes, discipline is maintained on campus.",
    "dress code hai": "Formal dress is preferred.",
    "hostel timing kya hai": "Hostel gate closes at 9 PM.",
    "placement percentage kya hai": "Placement percentage is good every year.",
    "highest package kitna hai": "Highest package details are available on website.",
    "average package kitna hai": "Average package is around 4-5 LPA.",
    "companies aati hai": "Yes, many companies visit for placements.",
    "tcs aati hai": "Yes, TCS visits for placements.",
    "infosys aati hai": "Yes, Infosys visits for placements.",
    "wipro aati hai": "Yes, Wipro visits for placements.",
    "coding competition hoti hai": "Yes, coding competitions are organized.",
    "seminar hote hai": "Yes, seminars are conducted regularly.",
    "workshop hoti hai": "Yes, workshops are organized frequently.",
    "faculty qualification kya hai": "Faculty members are highly qualified.",
    "campus bada hai": "Yes, the campus is large and modern.",
    "parking available hai": "Yes, parking facility is available.",
    "security achi hai": "Yes, campus security is available 24/7.",
    "cctv hai": "Yes, CCTV surveillance is installed.",
    "college safe hai": "Yes, campus safety is maintained properly.",
    "ncc available hai": "Yes, NCC activities are available.",
    "nss available hai": "Yes, NSS activities are available.",
    "industrial visit hoti hai": "Yes, industrial visits are organized.",
    "project banana hota hai": "Yes, final year projects are mandatory.",
    "viva hota hai": "Yes, viva exams are conducted.",
    "assignment compulsory hai": "Yes, assignments are compulsory.",
    "internal marks milte hai": "Yes, internal assessment marks are included.",
    "cgpa important hai": "Yes, CGPA is important for placements.",
    "minimum passing marks kya hai": "Minimum passing marks are 33%.",
    "classroom smart hai": "Yes, smart classrooms are available.",
    "air conditioned classroom hai": "Yes, AC classrooms are available.",
    "college me lift hai": "Yes, lift facility is available.",
    "digital library hai": "Yes, digital library access is available.",
    "biometric attendance hai": "Yes, biometric attendance system is used.",
    "clubs available hai": "Yes, many student clubs are available.",
    "music club hai": "Yes, music club is available.",
    "dance club hai": "Yes, dance club is available.",
    "photography club hai": "Yes, photography club is available.",
    "freshers party hoti hai": "Yes, freshers party is organized every year.",
    "farewell hota hai": "Yes, farewell events are organized.",
    "anti ragging cell hai": "Yes, anti-ragging cell is active.",
    "mentor milta hai": "Yes, mentors are assigned to students.",
    "campus interview hota hai": "Yes, campus interviews are conducted.",
    "english communication classes hai": "Yes, communication skill classes are available.",
    "personality development hota hai": "Yes, personality development sessions are conducted.",
    "college acha hai": "Yes, the college provides good facilities and education."
}
